---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: Verify Nginx installation
  command: nginx -v
  register: nginx_version
  changed_when: false
  failed_when: false
  no_log: false

- name: Display Nginx version
  debug:
    var: nginx_version.stderr
  no_log: false